name: checkout
on: push
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      branch: main
    steps:
      - run: echo "Checking out branch ${{ env.branch }}"
      - uses: actions/checkout@v2
        with:
          repository: ikkiHarrington/sampleSh
          ref: ${{ env.branch }}
          token: ${{ secrets.GITHUB_TOKEN }}