name: If
on: push
jobs:
  runOnlyIkki:
    runs-on: ubuntu-latest
    steps:
      - name: Show message
        if: ${{ github.actor == 'ikkiHarrington' }}
        run: echo "Only Ikki Harrington can see this message."